import type { LiveChannel } from './api';

export const WORKING_LIVE_CHANNELS: LiveChannel[] = [
  {
    id: 'nasa-tv',
    name: 'NASA TV Public',
    logo: 'NASA',
    category: 'Documentary',
    streamUrl: 'https://ntv1.akamaized.net/hls/live/2014075/NASA-NTV1-Public/master.m3u8',
    isLive: true,
    currentProgram: 'NASA Live Programming',
    nextProgram: 'Space and science coverage',
  },
  {
    id: 'nasa-media',
    name: 'NASA Media Channel',
    logo: 'NASA',
    category: 'Documentary',
    streamUrl: 'https://ntv1.akamaized.net/hls/live/2014075/NASA-NTV1-Media/master.m3u8',
    isLive: true,
    currentProgram: 'NASA Media Feed',
    nextProgram: 'Mission coverage',
  },
  {
    id: 'aljazeera',
    name: 'Al Jazeera English',
    logo: 'AJE',
    category: 'News',
    streamUrl: 'https://live-hls-web-aje.getaj.net/AJE/index.m3u8',
    isLive: true,
    currentProgram: 'Live World News',
    nextProgram: 'International headlines',
  },
  {
    id: 'france24-en',
    name: 'France 24 English',
    logo: 'F24',
    category: 'News',
    streamUrl: 'https://static.france24.com/live/F24_EN_LO_HLS/live_web.m3u8',
    isLive: true,
    currentProgram: 'Live News',
    nextProgram: 'World update',
  },
  {
    id: 'redbull-tv',
    name: 'Red Bull TV',
    logo: 'RBTV',
    category: 'Sports',
    streamUrl: 'https://rbmn-live.akamaized.net/hls/live/590964/BoRB-AT/master.m3u8',
    isLive: true,
    currentProgram: 'Action Sports and Culture',
    nextProgram: 'Live events and highlights',
  },
  {
    id: 'fifa-plus',
    name: 'FIFA Plus FAST',
    logo: 'FIFA',
    category: 'Sports',
    streamUrl: 'https://a62dad94a1df4f5f9b82cc8f48cb4e4f.mediatailor.us-east-1.amazonaws.com/v1/master/12d01d0d7be59d09ad07a23b58a30dd33edabb42/Samsung-gb_FIFAPlus/playlist.m3u8',
    isLive: true,
    currentProgram: 'Football Stories and Highlights',
    nextProgram: 'Match classics',
  },
  {
    id: 'poker-night',
    name: 'Poker Night Sports',
    logo: 'PN',
    category: 'Sports',
    streamUrl: 'https://dai.google.com/linear/hls/event/BB3OqImHTm6xkPGOZw1nRA/master.m3u8',
    isLive: true,
    currentProgram: 'Live Card Sports',
    nextProgram: 'Tournament coverage',
  },
  {
    id: 'kids-flix',
    name: 'Kids Zone FAST',
    logo: 'KIDS',
    category: 'Kids',
    streamUrl: 'https://dai.google.com/linear/hls/event/ysdq5SNUR7m8hi5gI3Rj9A/master.m3u8',
    isLive: true,
    currentProgram: 'Family Friendly Cartoons',
    nextProgram: 'Kids programming',
  },
  {
    id: 'battery-pop',
    name: 'BatteryPOP Kids',
    logo: 'BPOP',
    category: 'Kids',
    streamUrl: 'https://dai.google.com/linear/hls/event/0pG7JnoJQpCrKn3DWYuQKw/master.m3u8',
    isLive: true,
    currentProgram: 'Kids Entertainment',
    nextProgram: 'Short-form family shows',
  },
  {
    id: 'vevo-pop',
    name: 'Vevo Pop',
    logo: 'VEVO',
    category: 'Music',
    streamUrl: 'https://dai.google.com/linear/hls/event/8a4f4fa4e3b54684aef6f22c4dc5bd4f/master.m3u8',
    isLive: true,
    currentProgram: 'Pop Music Videos',
    nextProgram: 'Music rotation',
  },
  {
    id: 'failarmy',
    name: 'FailArmy',
    logo: 'FAIL',
    category: 'Entertainment',
    streamUrl: 'https://dai.google.com/linear/hls/event/9J1ub0HFT3iW3b_RoWQRsQ/master.m3u8',
    isLive: true,
    currentProgram: 'Viral Entertainment',
    nextProgram: 'Comedy clips',
  },
  {
    id: 'movie-sphere',
    name: 'MovieSphere FAST',
    logo: 'MS',
    category: 'Movies',
    streamUrl: 'https://dai.google.com/linear/hls/event/DeU2sP3RR1KZ2d0e4ZgG5A/master.m3u8',
    isLive: true,
    currentProgram: 'Free Movies',
    nextProgram: 'Feature films',
  },
];

export function findLiveChannel(id: string): LiveChannel | undefined {
  return WORKING_LIVE_CHANNELS.find((channel) => channel.id === id);
}
